version: '3'

services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://${GITLAB_DOMAIN}'
        registry_external_url 'https://${GITLAB_REGISTRY_DOMAIN}'
        registry_nginx['listen_port'] = 80
        registry_nginx['listen_https'] = false
        registry_nginx['proxy_set_headers'] = { "X-Forwarded-Proto" => "https", "X-Forwarded-Ssl" => "on" }
        nginx['listen_port'] = 80
        nginx['listen_https'] = false
        nginx['proxy_set_headers'] = { "X-Forwarded-Proto" => "https", "X-Forwarded-Ssl" => "on" }
        gitlab_rails['smtp_enable'] = true
        gitlab_rails['smtp_address'] = "${SMTP_SERVER}"
        gitlab_rails['smtp_port'] = ${SMTP_PORT}
        gitlab_rails['smtp_user_name'] = "${SMTP_USER}"
        gitlab_rails['smtp_password'] = "${SMTP_PASSWORD}"
        gitlab_rails['smtp_domain'] = "${SMTP_DOMAIN}"
        gitlab_rails['gitlab_email_from'] = "${FROM_MAIL}"
        gitlab_rails['gitlab_email_reply_to'] = "${REPLY_TO_MAIL}"
        gitlab_rails['smtp_authentication'] = "${SMTP_AUTH}"
        gitlab_rails['smtp_enable_starttls_auto'] = "${STARTTLS}"
        gitlab_rails['gitlab_shell_ssh_port'] = 22
      GITLAB_ROOT_PASSWORD: ${GITLAB_ROOT_PW}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.entrypoints=http"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule=Host(`${GITLAB_DOMAIN}`) || Host(`${GITLAB_REGISTRY_DOMAIN}`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.middlewares=https-redirect@file"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-secure.entrypoints=https"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-secure.rule=Host(`${GITLAB_DOMAIN}`) || Host(`${GITLAB_REGISTRY_DOMAIN}`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-secure.middlewares=secured@file"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-secure.tls=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-secure.tls.certresolver=http"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-secure.service=gitlab"
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}.loadbalancer.server.port=80"
      - "traefik.docker.network=${PROXY_NETWORK}"
    volumes:
      - ${CONTAINERVOLUME}/config:/etc/gitlab
      - ${CONTAINERVOLUME}/log:/var/log/gitlab
      - ${CONTAINERVOLUME}/data:/var/opt/gitlab
    networks:
      - proxy
    ports:
      - ${PROXY_PORT_SSH}:22

networks:
  proxy:
    external:
      name: ${PROXY_NETWORK}
